# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

boolean:代表布尔型，‘True, False’;  
float:代表浮点型，带有小数点；  
int:代表整数型，没有小数点

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [80]:
lst = [item if item%2==1 else -item for item in range(1,100) ]
print(lst)

[1, -2, 3, -4, 5, -6, 7, -8, 9, -10, 11, -12, 13, -14, 15, -16, 17, -18, 19, -20, 21, -22, 23, -24, 25, -26, 27, -28, 29, -30, 31, -32, 33, -34, 35, -36, 37, -38, 39, -40, 41, -42, 43, -44, 45, -46, 47, -48, 49, -50, 51, -52, 53, -54, 55, -56, 57, -58, 59, -60, 61, -62, 63, -64, 65, -66, 67, -68, 69, -70, 71, -72, 73, -74, 75, -76, 77, -78, 79, -80, 81, -82, 83, -84, 85, -86, 87, -88, 89, -90, 91, -92, 93, -94, 95, -96, 97, -98, 99]


In [19]:
sum(lst)

50

1.3  将字符串 s="yoyo" 转换成列表

In [16]:
s = 'yoyo'
list(s)

['y', 'o', 'y', 'o']

# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

### 答： 
首先是得到了1至99的整数list1；  
然后对list1进行切片，即从3开始，每隔3个数取一个值，直到99，得到list2；  
最后取list2的最后10个数，并通过循环进行print

In [20]:
for i in range(1,100)[2::3][-10:]:
    print(i)

72
75
78
81
84
87
90
93
96
99


2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [25]:
class Get_gap(object):
    def __init__(self,name,price_tuple):
        self.high_price = price_tuple[0]
        self.close_price = price_tuple[1]
        self.result = {name+'_dif':self.high_price-self.close_price}
        print(self.result)

In [26]:
gap1 = Get_gap("one", (15, 7))
gap2 = Get_gap("two", (66, 20))

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

### 答：
    (1) 查看列名：df.columns  
    (2) 对数据转置：df.T

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [36]:
# 引入pandas，并读取600029这只股票的数据
import pandas as pd
data = pd.read_excel('sz50.xlsx',sheet_name='600029.XSHG', index_col='datetime')
data_close = data.close

In [81]:
#引入numpy，并将收盘价转换成numpy的array格式
import numpy as np
data_close_arr = np.array(data_close)
print(type(data_close_arr))
data_close_arr[:5] # 收盘价的最后5个值

<class 'numpy.ndarray'>


array([11.64, 11.72, 11.8 , 11.8 , 11.85])

In [82]:
#引入 talib，并计算10日的EMA
import talib as ta
ema_close = ta.EMA(data_close_arr, timeperiod=10)
#输出EMA这个ndarray的最后五个值
print(type(ema_close))
print(ema_close[-5:])

<class 'numpy.ndarray'>
[15.08227205 15.2564044  15.44433088 15.72172526 15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [55]:
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheet_name=s, index_col='datetime')
    data_dict[s] = data
PN = pd.Panel(data_dict)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [70]:
arr_from_PN = np.array(PN) # 把Panel转成ndim为3的Numpy
print(arr_from_PN.shape)
arr_ndim2 = arr_from_PN[:,-20:,0]  # 用array的切片读取ndim为2的三只股票最近20天的收盘价
print(arr_ndim2)

(3, 215, 5)
[[ 13.85  13.82  13.83  14.11  14.25  14.39  15.1   15.15  15.22  14.97
   14.89  14.99  14.71  15.07  15.35  16.    16.04  16.29  16.97  17.05]
 [  8.53   8.56   8.62   8.88   9.25   9.24   9.43   9.25   9.02   9.15
    9.63   9.5    9.9    9.97   9.96   9.49   9.68   9.61   9.63   9.8 ]
 [134.83 134.56 137.5  143.18 143.48 144.15 143.61 143.65 144.35 143.36
  146.41 144.71 148.56 156.53 157.12 157.72 154.99 163.52 168.58 169.57]]


In [71]:
print(arr_from_PN.ndim)  # 从panel转为了ndim为3的numpy
print(arr_ndim2.ndim)   # 通过切片提取了一个ndim为2的array

3
2


3.5 建立一个5*5的矩阵，值从0到24

In [57]:
import numpy as np
lst = np.arange(0,25)
print(lst.reshape(5,5))  # 前行后列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
